import type { AcademyState, Course, Lesson } from "./model";
const intro = "Esta é uma atividade de demonstração para validar a experiência da DOC-Academy. O conteúdo técnico será cadastrado e revisado pela DeMaria antes da publicação oficial.\n\nNa versão de apresentação, você pode experimentar a sequência de aulas, marcar uma leitura como concluída e enviar uma avaliação de exemplo. Seu progresso fica apenas neste navegador.";
const lessons = (prefix: string): Lesson[] => [
  { id: `${prefix}-1`, title: "Boas-vindas à jornada", module: "01 · Comece por aqui", minutes: 4, type: "reading", content: intro, videoUrl: "" },
  { id: `${prefix}-2`, title: "Conhecendo o ambiente", module: "01 · Comece por aqui", minutes: 8, type: "video", content: "Espaço reservado para um vídeo da DeMaria. Vincule um link do Vimeo pelo editor do curso.", videoUrl: "" },
  { id: `${prefix}-3`, title: "Conceitos e possibilidades", module: "02 · Conhecimento na prática", minutes: 10, type: "reading", content: intro, videoUrl: "" },
  { id: `${prefix}-4`, title: "Da teoria à prática", module: "02 · Conhecimento na prática", minutes: 12, type: "video", content: "Esta aula receberá o conteúdo oficial do produto. A conclusão manual está disponível somente para experimentar esta demonstração.", videoUrl: "" },
  { id: `${prefix}-5`, title: "Consolide seu aprendizado", module: "03 · Próximo nível", minutes: 5, type: "quiz", content: "Avaliação de exemplo sobre a experiência da plataforma, sem conteúdo técnico de produto.", videoUrl: "" },
];
const base: Omit<Course, "id" | "title" | "description" | "product" | "accent" | "lessons"> = {
  category: "Produtos", level: "Essencial", status: "published", xp: 420, required: false, banner: "", author: "Equipe DOC-Academy", passingScore: 70, retryPolicy: "free", version: 1,
  audience: "internal", requiredModules: [], isSelagem: false,
  hasProficiencyTest: false, proficiencyScore: 85, proficiencyQuestions: [],
  questions: [
    { id: "q1", prompt: "Onde você encontra a sequência de aulas nesta demonstração?", type: "choice", options: ["No programa do curso, ao lado da atividade", "Somente no painel administrativo", "A sequência não está disponível"], correct: "No programa do curso, ao lado da atividade" },
    { id: "q2", prompt: "O que tornaria esta experiência de aprendizado mais útil no seu dia a dia?", type: "text", options: [], correct: "" },
  ],
};
export const initialState: AcademyState = {
  schema: 1,
  courseDrafts: [], articleDrafts: [],
  courses: [
    { ...base, id: "doc-windows", title: "Primeiros passos com o DOC-Windows", description: "Uma jornada para conhecer o produto e construir uma base sólida para o dia a dia.", product: "DOC-Windows", department: "Comercial", accent: "violet", required: true, lessons: lessons("win") },
    { ...base, id: "multiscan", title: "Digitalização com propósito", description: "Organize seu aprendizado sobre o DOC-MultiScan, do primeiro contato à prática.", product: "DOC-MultiScan", department: "Comercial", accent: "mint", xp: 360, lessons: lessons("scan") },
    { ...base, id: "atendimento", title: "Atendimento que gera confiança", description: "Comunicação, escuta e conhecimento para uma experiência de atendimento melhor.", product: "Conhecimentos gerais", category: "Desenvolvimento", department: "Comercial", accent: "peach", xp: 280, lessons: lessons("service") },
    { ...base, id: "rotinas", title: "O universo dos cartórios", description: "Uma introdução aos temas e rotinas que fazem parte do nosso trabalho.", product: "Conhecimentos gerais", category: "Cartórios", department: "Geral", accent: "blue", xp: 320, lessons: lessons("cart") },
    { ...base, id: "seguranca", title: "Cuidado com a informação", description: "Um espaço para aprender boas práticas e aprofundar o cuidado com os dados.", product: "Conhecimentos gerais", category: "Desenvolvimento", department: "Geral", accent: "pink", xp: 240, lessons: lessons("sec") },
    { ...base, id: "atualizacoes", title: "Sempre em evolução", description: "Uma trilha de atualização contínua para acompanhar novas possibilidades.", product: "DOC-Windows", level: "Intermediário", department: "Financeiro", accent: "slate", xp: 380, lessons: lessons("up") },
    {
      ...base,
      id: "client-win-casamento",
      title: "DOC-Windows: Módulo Casamento e Processos de Habilitação",
      description: "Capacitação completa na emissão de editais, proclamação e termos de casamento civil no sistema DOC-Windows.",
      product: "DOC-Windows",
      category: "Sistemas DeMaria",
      audience: "client" as const,
      requiredModules: ["WIN:C"],
      accent: "violet" as const,
      lessons: [
        { id: "win-cas-1", title: "Visão Geral do Módulo Casamento", module: "01 · Operação Básica", minutes: 6, type: "reading", content: "Orientações fundamentais para operação do módulo de Casamento no DOC-Windows.", videoUrl: "" },
        { id: "win-cas-2", title: "Autuação e Habilitação de Casamento", module: "01 · Operação Básica", minutes: 12, type: "video", content: "Passo a passo no preenchimento de noivos e testemunhas.", videoUrl: "" },
        { id: "win-cas-3", title: "Emissão de Termo e Livro D", module: "02 · Lavratura e Livro", minutes: 10, type: "video", content: "Finalização do registro e confecção do termo oficial.", videoUrl: "" },
        { id: "win-cas-4", title: "Avaliação Prática do Módulo Casamento", module: "03 · Certificação", minutes: 5, type: "quiz", content: "Avaliação para emissão da certificação do módulo Casamento.", videoUrl: "" },
      ],
    },
    {
      ...base,
      id: "client-selagem",
      title: "Controle e Aplicação de Selagem Digital Notarial e Registral",
      description: "Treinamento oficial sobre selagem eletrônica e comunicação com a Corregedoria Geral de Justiça do seu Estado.",
      product: "DOC-Windows",
      category: "Sistemas DeMaria",
      audience: "client" as const,
      requiredModules: ["WIN:S", "WEB:S"],
      isSelagem: true,
      accent: "mint" as const,
      lessons: [
        { id: "sel-geral-1", title: "Fundamentos da Selagem Eletrônica nos Sistemas DeMaria", module: "01 · Conceitos e Operação", minutes: 5, type: "reading", content: "Visão geral da rotina de selagem, controle de estoque de selos e auditoria interna.", videoUrl: "" },
        { id: "sel-sp-2", title: "Regras de Selagem Digital para o Estado de São Paulo (TJ-SP)", module: "02 · Selagem Estadual Específica", minutes: 15, type: "video", content: "Aula gravada especificamente para as regras da CGJ do Tribunal de Justiça de São Paulo.", videoUrl: "", ufFilter: ["SP"] },
        { id: "sel-rj-2", title: "Regras de Selagem Eletrônica para o Rio de Janeiro (CGJ-RJ)", module: "02 · Selagem Estadual Específica", minutes: 14, type: "video", content: "Aula gravada especificamente para as regras da CGJ do Tribunal de Justiça do Rio de Janeiro.", videoUrl: "", ufFilter: ["RJ"] },
        { id: "sel-mg-2", title: "Regras de Selagem Eletrônica e SISNOR para Minas Gerais (TJ-MG)", module: "02 · Selagem Estadual Específica", minutes: 16, type: "video", content: "Aula gravada especificamente para as regras da CGJ do Tribunal de Justiça de Minas Gerais.", videoUrl: "", ufFilter: ["MG"] },
        { id: "sel-quiz-3", title: "Avaliação do Módulo de Selagem Digital", module: "03 · Certificação", minutes: 5, type: "quiz", content: "Avaliação de conhecimento sobre selagem no sistema.", videoUrl: "" },
      ],
    },
    {
      ...base,
      id: "client-aol-certidoes",
      title: "Atendimento Online (AOL): Pedidos de Certidão e Integração CRC",
      description: "Operação completa de recepção, processamento e envio de certidões eletrônicas recebidas via portal AOL.",
      product: "Atendimento Online (AOL)",
      category: "Sistemas DeMaria",
      audience: "client" as const,
      requiredModules: ["AOL:D"],
      accent: "peach" as const,
      lessons: [
        { id: "aol-1", title: "Configuração do Portal de Pedidos de Certidão", module: "01 · Recepção Online", minutes: 8, type: "video", content: "Como parametrizar prazos, taxas e notificações ao cidadão.", videoUrl: "" },
        { id: "aol-2", title: "Fluxo de Resposta e Envio de Certidões", module: "02 · Expedição", minutes: 10, type: "video", content: "Atendimento e emissão de certidão digital em PDF assinado.", videoUrl: "" },
        { id: "aol-3", title: "Avaliação do Módulo de Pedidos de Certidão", module: "03 · Certificação", minutes: 5, type: "quiz", content: "Avaliação do módulo AOL.", videoUrl: "" },
      ],
    },
  ],
  articles: [
    { id: "como-consultar", title: "Como consultar a base de conhecimento", product: "DOC-Academy", category: "Guia da plataforma", status: "published", revision: 1, updatedAt: "2026-09-14", author: "Equipe DOC-Academy", content: "Nesta demonstração, todos os colaboradores podem consultar os artigos publicados. Use a pesquisa por título, produto ou palavras do conteúdo.\n\nAo abrir um artigo, você encontra o responsável, a data de atualização e a versão publicada. A consulta assistida por IA será conectada na etapa de integração; a busca disponível aqui é textual.\n\nEste artigo descreve a demonstração da plataforma. Não é um manual de produto ou uma orientação técnica de cartório." },
    { id: "sua-jornada", title: "Entenda sua jornada de aprendizado", product: "DOC-Academy", category: "Aprendizado", status: "published", revision: 1, updatedAt: "2026-09-14", author: "Equipe DOC-Academy", content: "A área Aprender reúne os cursos publicados. Cada curso tem uma página com objetivo e programa de atividades.\n\nVocê pode salvar um curso para depois e continuar suas atividades na sala de aula. Aulas concluídas e aprovação na avaliação são estados separados.\n\nNesta apresentação, o progresso é demonstrativo e fica salvo neste navegador. Nenhum certificado oficial é emitido." },
    { id: "novas-conquistas", title: "Uma nova temporada, novas conquistas", product: "DOC-Academy", category: "Conquistas", status: "published", revision: 1, updatedAt: "2026-09-14", author: "Equipe DOC-Academy", content: "O desenho de gamificação diferencia trajetória acumulada e participação em cada temporada anual. As conquistas anteriores permanecem no histórico.\n\nOs valores de XP e as faixas desta demonstração são ilustrativos. A calibragem oficial será feita conforme o conteúdo disponível.\n\nAs estatísticas e pessoas exibidas no ranking são exemplos para validar a interface." },
  ],
  departments: ["Comercial", "Financeiro", "Desenvolvimento WIN", "Suporte técnico"], products: ["DOC-Windows", "DOC-MultiScan", "Conhecimentos gerais", "DOC-Academy"],
  people: [
    { id: "daniel", name: "Daniel", email: "daniel@example.com", department: "Comercial", managerId: "daniel", role: "admin", status: "active", xp: 1320, progress: 50, audience: "internal" },
    { id: "ana", name: "Ana Martins", email: "ana@example.com", department: "Comercial", managerId: "daniel", role: "student", status: "active", xp: 2860, progress: 88, audience: "internal" },
    { id: "lucas", name: "Lucas Oliveira", email: "lucas@example.com", department: "Comercial", managerId: "daniel", role: "student", status: "active", xp: 2540, progress: 75, audience: "internal" },
    { id: "mariana", name: "Mariana Costa", email: "mariana@example.com", department: "Financeiro", managerId: "mariana", role: "manager", status: "active", xp: 2280, progress: 68, audience: "internal" },
    { id: "pedro", name: "Pedro Santos", email: "pedro@example.com", department: "Financeiro", managerId: "mariana", role: "student", status: "active", xp: 1950, progress: 61, audience: "internal" },
    { id: "julia", name: "Júlia Lima", email: "julia@example.com", department: "Comercial", managerId: "daniel", role: "student", status: "active", xp: 1680, progress: 54, audience: "internal" },
    { id: "maria-cartorio", name: "Maria Helena Souza", email: "maria@cartoriosantos.com.br", department: "Cartório Cliente", managerId: "", role: "student", status: "active", xp: 540, progress: 60, audience: "client", cartorioId: "cart-santos-1" },
  ],
  completed: { "doc-windows": ["win-1", "win-2"], "multiscan": ["scan-1"] }, videoProgress: {}, bookmarks: ["atendimento"],
  attempts: [
    {
      id: "att-ana-1",
      userId: "ana",
      courseId: "doc-windows",
      courseTitle: "Primeiros passos com o DOC-Windows",
      courseVersion: 1,
      quizId: "win-5",
      questions: base.questions,
      answers: { q1: "No programa do curso, ao lado da atividade", q2: "Exemplos práticos de rotinas reais de cartório e integração com a base de conhecimento." },
      status: "approved",
      feedback: "Excelente desempenho! Domínio completo da navegação e conceitos.",
      score: 100,
      passingScore: 70,
      xp: 420,
      submittedAt: "2026-09-15T14:30:00Z",
      retryPolicy: "free",
      retryAllowed: false,
      correctTextIds: ["q2"],
    },
    {
      id: "att-lucas-1",
      userId: "lucas",
      courseId: "doc-windows",
      courseTitle: "Primeiros passos com o DOC-Windows",
      courseVersion: 1,
      quizId: "win-5",
      questions: base.questions,
      answers: { q1: "No programa do curso, ao lado da atividade", q2: "Vídeos mais curtos focados em dúvidas pontuais." },
      status: "approved",
      feedback: "Bom aproveitamento. Questões compreendidas com clareza.",
      score: 85,
      passingScore: 70,
      xp: 420,
      submittedAt: "2026-09-16T10:15:00Z",
      retryPolicy: "free",
      retryAllowed: false,
      correctTextIds: ["q2"],
    },
    {
      id: "att-julia-1",
      userId: "julia",
      courseId: "doc-windows",
      courseTitle: "Primeiros passos com o DOC-Windows",
      courseVersion: 1,
      quizId: "win-5",
      questions: base.questions,
      answers: { q1: "Somente no painel administrativo", q2: "Mais explicações sobre a navegação da plataforma." },
      status: "retry",
      feedback: "Atenção: a questão 1 foi assinalada incorretamente. A sequência de aulas fica no menu lateral de cada atividade, não no painel administrativo. Revise o Módulo 01.",
      score: 45,
      passingScore: 70,
      xp: 0,
      submittedAt: "2026-09-16T16:45:00Z",
      retryPolicy: "free",
      retryAllowed: true,
      correctTextIds: [],
    },
    {
      id: "att-pedro-1",
      userId: "pedro",
      courseId: "atualizacoes",
      courseTitle: "Sempre em evolução",
      courseVersion: 1,
      quizId: "up-5",
      questions: base.questions,
      answers: { q1: "No programa do curso, ao lado da atividade", q2: "Simulações de casos reais." },
      status: "approved",
      feedback: "Parabéns pela conclusão e pela dedicação ao treinamento contínuo.",
      score: 90,
      passingScore: 70,
      xp: 380,
      submittedAt: "2026-09-16T11:00:00Z",
      retryPolicy: "free",
      retryAllowed: false,
      correctTextIds: ["q2"],
    },
  ],
  teamProgress: {
    ana: {
      "doc-windows": ["win-1", "win-2", "win-3", "win-4"],
      "multiscan": ["scan-1", "scan-2", "scan-3", "scan-4"],
      "atendimento": ["service-1", "service-2", "service-3", "service-4"],
      "rotinas": ["cart-1", "cart-2", "cart-3", "cart-4"],
    },
    lucas: {
      "doc-windows": ["win-1", "win-2", "win-3", "win-4"],
      "multiscan": ["scan-1", "scan-2"],
      "atendimento": ["service-1", "service-2", "service-3"],
      "rotinas": ["cart-1", "cart-2", "cart-3"],
    },
    julia: {
      "doc-windows": ["win-1", "win-2", "win-3"],
      "atendimento": ["service-1", "service-2"],
      "seguranca": ["sec-1"],
    },
    pedro: {
      "atualizacoes": ["up-1", "up-2", "up-3", "up-4"],
      "seguranca": ["sec-1", "sec-2", "sec-3"],
      "rotinas": ["cart-1", "cart-2"],
    },
    mariana: {
      "atualizacoes": ["up-1", "up-2", "up-3", "up-4"],
      "seguranca": ["sec-1", "sec-2", "sec-3", "sec-4"],
      "rotinas": ["cart-1", "cart-2", "cart-3"],
    },
  },
  xpEvents: [{ id: "demo-start", amount: 1320, season: "2026", label: "Trajetória ilustrativa" }], readNotices: [], notifications: [],
  cartorios: [
    {
      id: "cart-santos-1",
      name: "1º Registro Civil das Pessoas Naturais de Santos",
      city: "Santos",
      uf: "SP",
      cns: "11.123-4",
      modules: ["WIN:C", "WIN:S", "AOL:D", "WEB:W", "ESP:k"],
      keyUserId: "maria-cartorio",
      keyUserName: "Maria Helena Souza",
      keyUserEmail: "maria@cartoriosantos.com.br",
      status: "active",
      createdAt: "2026-09-15T10:00:00Z",
    },
    {
      id: "cart-rio-2",
      name: "2º Ofício de Registro Civil e Notas da Capital",
      city: "Rio de Janeiro",
      uf: "RJ",
      cns: "08.456-7",
      modules: ["WIN:C", "WIN:S", "AOL:N", "AOL:O"],
      keyUserId: "carlos-cartorio",
      keyUserName: "Carlos Eduardo Mendes",
      keyUserEmail: "carlos@cartoriorio.com.br",
      status: "active",
      createdAt: "2026-09-16T11:00:00Z",
    },
  ],
};
