"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { browserAuth } from "@/lib/supabase-browser";
export function AccessScreen({configured,signedIn}:{configured:boolean;signedIn:boolean}){
 const router=useRouter();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirmation,setConfirmation]=useState("");const [forgot,setForgot]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function submit(event:React.FormEvent){event.preventDefault();setMessage("");const auth=browserAuth();if(!auth)return;setBusy(true);
  try{
   if(signedIn){if(password!==confirmation)throw new Error("As senhas precisam ser iguais.");if(password.length<12)throw new Error("Use uma senha com pelo menos 12 caracteres.");const result=await auth.auth.updateUser({password});if(result.error)throw result.error;setPassword("");setConfirmation("");router.replace("/");}
   else if(forgot){const result=await auth.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/acesso`});if(result.error)throw result.error;setMessage("Se este e-mail estiver cadastrado, você receberá as instruções para definir sua senha.");}
   else{const result=await auth.auth.signInWithPassword({email,password});if(result.error)throw new Error("Não foi possível entrar. Confira seu e-mail, senha e a confirmação do convite.");setPassword("");router.replace("/");}
  }catch(err){setMessage(err instanceof Error?err.message:"Não foi possível concluir. Tente novamente.");}finally{setBusy(false);}
 }
 return <main className="access-page"><section className="access-story"><a className="brand" href="/"><strong>DOC-<span>Academy</span></strong></a><span className="hero-eyebrow">DEMARIA · CONHECIMENTO QUE TRANSFORMA</span><h1>Seu próximo nível<br/>começa <em>aqui.</em></h1><p>Um espaço para aprender, compartilhar descobertas e evoluir com a sua equipe.</p><div className="hero-gem"><LockKeyhole size={70} strokeWidth={1}/></div></section><section className="panel access-card"><span className="eyebrow">SUA JORNADA NA DOC-ACADEMY</span><h2>{!configured?"Estamos preparando seu acesso":signedIn?"Defina sua senha":forgot?"Recupere seu acesso":"Bom ter você por aqui."}</h2><p>{!configured?"O administrador precisa concluir a configuração do Supabase neste ambiente. Nenhum dado de demonstração será usado como conta real.":signedIn?"Escolha uma senha pessoal para acessar seus cursos.":forgot?"Informe seu e-mail de trabalho para receber as instruções.":"Entre com seu e-mail e senha para continuar aprendendo."}</p>{configured&&<form onSubmit={submit}>{!signedIn&&<label className="field"><span>E-mail de trabalho</span><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="voce@demaria.com.br"/></label>}{(!forgot||signedIn)&&<label className="field"><span>{signedIn?"Nova senha":"Senha"}</span><input type="password" autoComplete={signedIn?"new-password":"current-password"} minLength={signedIn?12:undefined} value={password} onChange={e=>setPassword(e.target.value)} required/></label>}{signedIn&&<label className="field"><span>Confirme a nova senha</span><input type="password" autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} required/></label>}{message&&<p className="info-note" role="status">{message}</p>}<button className="button button-primary" type="submit" disabled={busy}>{busy?"Aguarde…":signedIn?"Salvar senha e entrar":forgot?"Enviar instruções":"Entrar na minha jornada"}<ArrowRight size={16}/></button>{!signedIn&&<button type="button" className="button button-ghost" onClick={()=>{setForgot(!forgot);setMessage("");}}>{forgot?"Voltar ao login":"Esqueci minha senha"}</button>}</form>}<div className="info-note">Acesso interno por convite. Precisa de ajuda? Fale com o administrador da DOC-Academy.</div></section></main>;
}
