"use client";
import Link from "next/link";
import { ArrowLeft, Award, BookOpen, CheckCircle2, Clock3, FileText, PlayCircle, ShieldCheck, Zap } from "lucide-react";
import { useAcademy } from "./academy-provider";
import { CourseArt, EmptyState, StudyButton, CheckLabel } from "./shared";
import { minutes } from "@/lib/model";
export function CourseDetail({ id }: { id: string }) {
  const { state, ready } = useAcademy(); const course = state.courses.find(item => item.id === id && item.status === "published");
  if (!ready) return <div className="empty-state">Preparando sua jornada…</div>;
  if (!course) return <EmptyState title="Este curso ainda não está disponível" description="Explore os cursos publicados no catálogo."/>;
  const completed = state.completed[id] || [];
  const modules = Array.from(new Set(course.lessons.map(lesson => lesson.module)));
  return <div className="page-enter"><Link className="back-link" href="/aprender"><ArrowLeft size={15}/> Voltar ao catálogo</Link><div className="detail-grid"><CourseArt course={course} large/><section className="detail-intro"><span className="pill">{course.product}</span><h1>{course.title}</h1><p>{course.description}</p><div className="detail-metrics"><span><Clock3 size={15}/>{minutes(course)} min</span><span><BookOpen size={15}/>{course.lessons.length} atividades</span><span><Zap size={15}/>Até {course.xp} XP</span></div><StudyButton course={course}>{completed.length ? "Continuar aprendendo" : "Começar minha jornada"}</StudyButton><div className="info-note">Conteúdo publicado pela DeMaria. Seu progresso e suas avaliações ficam salvos na sua conta.</div></section></div><div className="detail-grid"><section className="detail-section panel"><h2>Seu caminho neste curso</h2><div className="course-program">{course.lessons.map((lesson,position) => <div key={lesson.id}>{lesson.module&&course.lessons[position-1]?.module!==lesson.module&&<h3 className="module-title">{lesson.module}</h3>}<Link className="program-row" href={`/aprender/${id}/aula?aula=${lesson.id}`} key={lesson.id}>{completed.includes(lesson.id) ? <CheckCircle2 size={17}/> : lesson.type === "video" ? <PlayCircle size={17}/> : <FileText size={17}/>}<span>{lesson.title}</span><span>{lesson.minutes} min</span></Link></div>)}</div></section><section className="detail-section panel" style={{ alignSelf: "start" }}><h2>Aprender e evoluir</h2><CheckLabel>Acesso livre ao conteúdo interno publicado</CheckLabel><CheckLabel>Retomada da sequência de atividades</CheckLabel><CheckLabel>{course.lessons.some(l=>l.type==="quiz") ? "Avaliação com feedback do administrador" : "Curso sem avaliação"}</CheckLabel><CheckLabel>XP por aula e +30 XP pela conclusão</CheckLabel><div className="info-note"><ShieldCheck size={17}/><strong> Cada etapa conta.</strong><br/>{course.lessons.some(l=>l.type==="quiz") ? `Nota mínima: ${course.passingScore}%. Acertos valem 5 XP (objetiva) ou 8 XP (dissertativa). Aprovação: +30 XP na primeira tentativa, +10 XP após reprovação.` : "Conclua todas as aulas para finalizar o curso e receber o bônus de 30 XP."}</div><div className="course-duration"><span><Award size={14}/>{course.author}</span></div></section></div></div>;
}
