"use client";
import { isCourseComplete } from "@/lib/rewards";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Award, BookOpen, Check, ChevronRight, Flame, Gem, GraduationCap, Sparkles, Target, Trophy, Zap } from "lucide-react";
import { useAcademy } from "./academy-provider";
import { Button } from "./ui/button";
import { CourseCard, PageHeading, SectionHeading } from "./shared";
import { experience, DEMO_SEASON } from "@/lib/gamification";
import { courseProgress } from "@/lib/model";
import { initials, number } from "@/lib/utils";
export function Dashboard() {
  const { state, me } = useAcademy(); const courses = state.courses.filter(course => course.status === "published");
  const continuing = courses.filter(course => !isCourseComplete(course, state, me.id)).sort((a, b) => Number((state.completed[b.id] || []).length > 0) - Number((state.completed[a.id] || []).length > 0)).slice(0, 3);
  const active = courses.filter(course => (state.completed[course.id] || []).length > 0 && !isCourseComplete(course, state, me.id));
  const progress = active.length ? Math.round(active.reduce((sum, course) => sum + courseProgress(course, state.completed[course.id] || []), 0) / active.length) : 0;
  const evolution = experience(state); const xp = evolution.total; const approved = courses.filter(course => isCourseComplete(course, state, me.id));
  const people = state.people.filter(person => person.status === "active").map(person => person.id === me.id ? { ...person, xp: evolution.annual } : person).sort((a, b) => b.xp - a.xp);
  return <div className="page-enter"><PageHeading title={`Bom te ver por aqui, ${me.name.split(" ")[0]}`} description="Cada aprendizado é um passo para ir além."><span className="season-pill"><span/> Temporada {DEMO_SEASON} <Sparkles size={14}/></span></PageHeading>
    <div className="welcome-grid"><section className="hero" onPointerMove={event=>{if(event.pointerType!=="mouse"||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const bounds=event.currentTarget.getBoundingClientRect();event.currentTarget.style.setProperty("--hero-x",`${((event.clientX-bounds.left)/bounds.width-.5)*10}px`);event.currentTarget.style.setProperty("--hero-y",`${((event.clientY-bounds.top)/bounds.height-.5)*8}px`);}} onPointerLeave={event=>{event.currentTarget.style.setProperty("--hero-x","0px");event.currentTarget.style.setProperty("--hero-y","0px");}}><div className="hero-copy"><div className="hero-eyebrow"><span/> O SEU PRÓXIMO NÍVEL</div><h2>Conhecimento que<br/>transforma <em>você.</em></h2><p>Explore possibilidades, desenvolva suas habilidades<br className="desktop-only"/> e construa sua próxima conquista.</p><Button asChild variant="mint"><Link href="/aprender">Continuar minha jornada <ArrowRight size={17}/></Link></Button><div className="hero-foot"><span className="hero-avatars"><i>A</i><i>L</i><i>M</i></span><span>Aprender é melhor quando evoluímos juntos.</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="hero-aura"/><div className="hero-gem"><Gem size={88} strokeWidth={.85}/></div><span className="floating-chip chip-xp"><Zap size={16} fill="currentColor"/> + conhecimento</span><span className="floating-chip chip-level"><span><GraduationCap size={22}/></span><span>SEMPRE EM<br/><strong>evolução</strong></span></span><span className="hero-star star-one">✦</span><span className="hero-star star-two">✧</span><span className="hero-star star-three">✦</span></div></section>
    <section className="journey-card panel"><div className="section-title"><h3>Sua jornada</h3><span className="icon-muted"><Target size={18}/></span></div><div className="journey-ring"><svg viewBox="0 0 140 140" aria-hidden="true"><circle className="ring-track" cx="70" cy="70" r="58"/><circle className="ring-fill" cx="70" cy="70" r="58" strokeDasharray={`${progress * 3.644} 364.4`} transform="rotate(-90 70 70)"/></svg><div><strong>{progress}<small>%</small></strong><span>das aulas iniciadas</span></div></div><div className="journey-stats"><div><span className="mini-icon violet"><BookOpen size={17}/></span><span><strong>{active.length}</strong><small>em andamento</small></span></div><div><span className="mini-icon mint"><Award size={17}/></span><span><strong>{approved.length}</strong><small>cursos concluídos</small></span></div></div><Link href="/conquistas" className="journey-link">Ver minha evolução <ArrowUpRight size={16}/></Link></section></div>
    <div className="metric-strip"><div><span className="metric-icon"><Zap size={20}/></span><span><small>Experiência acumulada</small><strong>{number(xp)} <em>XP</em></strong></span><span className="metric-tag">Sua trajetória</span></div><div><span className="metric-icon"><GraduationCap size={22}/></span><span><small>Aprender, a cada passo</small><strong>Nível {evolution.level} <em>· Explorador</em></strong></span></div><div><span className="metric-icon"><Trophy size={20}/></span><span><small>Conquista da temporada</small><strong>{evolution.tier.name} <em>· {DEMO_SEASON}</em></strong></span><Link href="/conquistas" aria-label="Conhecer metas da temporada"><ChevronRight size={20}/></Link></div></div>
    <section className="dashboard-courses"><SectionHeading title="Continue de onde parou" description="Seu próximo aprendizado está logo aqui." href="/aprender" link="Explorar catálogo"/><div className="course-grid">{continuing.map(course => <CourseCard key={course.id} course={course}/>)}</div></section>
    <div className="dashboard-bottom"><section className="knowledge-callout"><div className="knowledge-symbol"><Sparkles size={26}/></div><span className="eyebrow">CONHECIMENTO AO SEU ALCANCE</span><h2>Uma dúvida. Novas possibilidades.</h2><p>Encontre os guias e materiais que ajudam você<br className="desktop-only"/> a seguir em frente, no seu ritmo.</p><Button asChild variant="secondary"><Link href="/conhecimento">Explorar conhecimento <ArrowRight size={16}/></Link></Button><div className="knowledge-lines" aria-hidden="true"><i/><i/><i/></div><span className="coming-label">Consulta com IA em preparação</span></section><section className="ranking-card panel"><SectionHeading title="Quem está indo além" href="/conquistas" link="Ranking"/><div className="ranking-subtitle"><Trophy size={14}/> Destaques da temporada <span>XP de aprendizado</span></div>{people.slice(0, 5).map((person, index) => <div className="ranking-row" key={person.id}><span className={`rank-position rank-${index + 1}`}>{index === 0 ? <Trophy size={15}/> : String(index + 1).padStart(2, "0")}</span><span className={`avatar avatar-${index}`}>{initials(person.name)}</span><span className="ranking-name"><strong>{person.name}</strong><small>{person.department}</small></span><span className="ranking-xp">{number(person.xp)} <small>XP</small></span></div>)}</section></div>
    <div className="bottom-note"><span><Check size={16}/> Seu aprendizado, no seu ritmo.</span><p>As pequenas descobertas de hoje constroem as grandes conquistas de amanhã.</p><Flame size={18}/></div>
  </div>;
}


