"use client";
import { useState } from "react";
import { Download, Search, Target, TrendingUp, Users } from "lucide-react";
import { useAcademy } from "./academy-provider";
import { Button } from "./ui/button";
import { PageHeading, Progress, EmptyState } from "./shared";
import { csvCell, initials, normalize } from "@/lib/utils";
export function Team() {
  const { state, notify } = useAcademy(); const [search, setSearch] = useState("");
  const people = state.people.filter(person => person.managerId === "daniel" && person.id !== "daniel" && person.status !== "inactive");
  const filtered = people.filter(person => normalize(`${person.name} ${person.department}`).includes(normalize(search)));
  const progress = people.length ? Math.round(people.reduce((sum, person) => sum + person.progress, 0) / people.length) : 0;
  const exportReport = () => { const lines = [["Nome", "Departamento", "Progresso demonstrativo (%)", "XP demonstrativo"].map(csvCell).join(";"), ...filtered.map(person => [person.name, person.department, person.progress, person.xp].map(csvCell).join(";"))]; const url = URL.createObjectURL(new Blob(["\uFEFF" + lines.join("\r\n")], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "doc-academy-equipe-demonstracao.csv"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); notify("Relatório demonstrativo exportado."); };
  return <div className="page-enter"><PageHeading eyebrow="EVOLUIR EM CONJUNTO" title="Cada pessoa faz a diferença." description="Acompanhe sua equipe e ajude a transformar aprendizado em evolução."><Button variant="secondary" onClick={exportReport}><Download size={15}/> Exportar relatório</Button></PageHeading><div className="admin-stats" style={{ gridTemplateColumns: "repeat(3,1fr)" }}>{[{ title: "Pessoas na equipe", value: people.length, icon: Users }, { title: "Progresso médio", value: `${progress}%`, icon: TrendingUp }, { title: "Em desenvolvimento", value: people.filter(person => person.progress > 0 && person.progress < 100).length, icon: Target }].map(item => <section key={item.title} className="panel stat-card"><span>{item.title}<item.icon size={17}/></span><strong>{item.value}</strong><small>Dados de demonstração</small></section>)}</div><div className="filter-bar"><div className="field-search"><Search size={17}/><input aria-label="Buscar pessoa na minha equipe" placeholder="Buscar pessoa ou departamento..." value={search} onChange={event => setSearch(event.target.value)}/></div></div>{filtered.length ? <div className="table-wrap"><table><thead><tr><th>COLABORADOR</th><th>DEPARTAMENTO</th><th>PROGRESSO</th><th>EXPERIÊNCIA</th><th>SITUAÇÃO</th></tr></thead><tbody>{filtered.map((person, index) => <tr key={person.id}><td><div className="table-person"><span className={`avatar avatar-${index}`}>{initials(person.name)}</span><div><strong>{person.name}</strong><small>{person.email}</small></div></div></td><td>{person.department}</td><td><div className="table-progress"><span>{person.progress}%</span><Progress value={person.progress} label={`Progresso de ${person.name}`}/></div></td><td>{person.xp.toLocaleString("pt-BR")} XP</td><td><span className={`pill ${person.status === "active" ? "green" : "amber"}`}>{person.status === "active" ? "Em jornada" : "Cadastro pendente"}</span></td></tr>)}</tbody></table></div> : <EmptyState icon={<Users size={28}/>} title="Nenhuma pessoa nesta busca" description="Ajuste o nome ou cadastre pessoas vinculadas ao gestor da demonstração."/>}<div className="info-note">Esta visão mostra os cadastros vinculados a Daniel, gestor de exemplo. Os relatórios são ilustrativos; o isolamento real entre contas depende da autenticação e das permissões no servidor.</div></div>;
}
